// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcxns54Sg1JshzJrUcfST1AsKYRT3kGJc',
    appId: '1:519871621128:web:0c71818b29570cb07c89bd',
    messagingSenderId: '519871621128',
    projectId: 'cube-flutter',
    authDomain: 'cube-flutter.firebaseapp.com',
    storageBucket: 'cube-flutter.appspot.com',
    measurementId: 'G-5LPMWVJH6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6C2ODGLQsdYEZKHBbIsq1MTe1s5u_AM0',
    appId: '1:519871621128:android:958772dc6d0d16557c89bd',
    messagingSenderId: '519871621128',
    projectId: 'cube-flutter',
    storageBucket: 'cube-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZyuHs11Dq2vliql6Vh1FYD73PQfHtXo',
    appId: '1:519871621128:ios:26c1005a9e2846db7c89bd',
    messagingSenderId: '519871621128',
    projectId: 'cube-flutter',
    storageBucket: 'cube-flutter.appspot.com',
    iosClientId: '519871621128-7o0t2ue9rvgb9ufd60l2anteklp8uanr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cube',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZyuHs11Dq2vliql6Vh1FYD73PQfHtXo',
    appId: '1:519871621128:ios:26c1005a9e2846db7c89bd',
    messagingSenderId: '519871621128',
    projectId: 'cube-flutter',
    storageBucket: 'cube-flutter.appspot.com',
    iosClientId: '519871621128-7o0t2ue9rvgb9ufd60l2anteklp8uanr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cube',
  );
}
